# Generated by Django 3.0.6 on 2020-05-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount', models.BooleanField(default=False)),
                ('bargain_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('number', models.IntegerField(default=1)),
                ('description', models.TextField(default=' no description', max_length=500)),
                ('category', models.ManyToManyField(related_name='what_category', to='shop.Category')),
            ],
        ),
    ]
