# Generated by Django 3.0.6 on 2020-05-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_descritpion',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
