# Generated by Django 3.0.6 on 2020-05-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.FileField(default=None, null=True, upload_to='static/img'),
        ),
    ]
