# Generated by Django 3.0.6 on 2020-05-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_short_descritpion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='short_descritpion',
            new_name='short_description',
        ),
    ]
