# Generated by Django 3.0.6 on 2020-05-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200525_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default=None, null=True, upload_to='static/img'),
        ),
    ]
