# Generated by Django 3.0.6 on 2020-05-30 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200530_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 13, 29, 22, 487289)),
        ),
    ]
