# Generated by Django 3.0.6 on 2020-05-23 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200523_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='full_description',
        ),
    ]
