# Generated by Django 3.0.6 on 2020-06-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200530_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_reverse',
            field=models.ImageField(default=None, null=True, upload_to='static/img/reverses'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default=None, null=True, upload_to='static/img/products'),
        ),
    ]
