# Generated by Django 3.0.6 on 2020-05-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetext',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
